apiVersion: batch/v1
kind: CronJob
metadata:
  name: google-books-search
  namespace: google-books-search
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          imagePullSecrets:
          - name: gcr-auth-details
          containers:
          - name: google-books
            image: gcr.io/ope-take-home/google-books-search:v1.0.1
            args: ["Kubernetes"]  # Example search term and result limit
            env:
            - name: GOOGLE_BOOKS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-api-secret
                  key: api-key
            resources:
              requests:
                memory: "128Mi"
                cpu: "100m"
              limits:
                memory: "256Mi"
                cpu: "500m"
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3