# Generate random 32 character password

resource "random_password" "postgres_password" {
  length  = 32
  special = true
}

# Create secret object in Google Secrets Manager

#resource "google_secret_manager_secret" "postgres_password" {
#  secret_id = "postgres-password"

#  replication {
#    user_managed {
#      replicas {
#        location = "us-central1"
#      }
#    }
#  }
#}

# Populate GSM object with data generated by random password resource

#resource "google_secret_manager_secret_version" "postgres_password" {
#  secret      = google_secret_manager_secret.postgres_password.id
#  secret_data = random_password.postgres_password.result
#}

# Create CloudSQL database instance

resource "google_sql_database_instance" "postgres" {
  name             = "pe-demo-postgres"
  database_version = "POSTGRES_15"
  region           = "us-central1"

  settings {
    tier = "db-f1-micro"

    insights_config {
      query_insights_enabled  = true   # Enables query analysis
      query_string_length     = 1024
      record_application_tags = true
      record_client_address   = true
    }
  }
}

# Create database on CloudSQL instance

resource "google_sql_database" "database" {
  name     = "pe-demo-db"
  instance = google_sql_database_instance.postgres.name
}

# Create pe-admin user on pe-dmeo-db database with random auto-generated password

resource "google_sql_user" "postgres_user" {
  name     = "pe-admin"
  instance = google_sql_database_instance.postgres.name
  password = random_password.postgres_password.result
}
