apiVersion: v1
kind: Service
metadata:
  name: pe-web
  namespace: pe-demo-app
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
  labels:
    app: pe-web
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: pe-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
